apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.configMap.APP_NAME | quote }}
  APP_VERSION: {{ .Values.configMap.APP_VERSION | quote }}
  ENVIRONMENT: {{ .Values.configMap.ENVIRONMENT | quote }}
