apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  GROQ_API_KEY: {{ .Values.secrets.GROQ_API_KEY | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  GROQ_BASE_URL: {{ .Values.secrets.GROQ_BASE_URL | quote }}
  GROQ_MODEL: {{ .Values.secrets.GROQ_MODEL | quote }}
